/**
 * pal_profile_list.cpp
 * PC-specific profile list — provides g_fpcPf_ProfileList_p population.
 * Only profiles compiled from Shield/splits.txt are available;
 * REL-only profiles are set to NULL (safely skipped by fpcBs_Create).
 */

#include "global.h"

#if PLATFORM_PC

#include "f_pc/f_pc_profile.h"
#include "f_pc/f_pc_profile_lst.h"  /* externs for all g_profile_* */
#include "f_op/f_op_scene_mng.h"
#include "d/d_procname.h"
#include "pal/pal_milestone.h"
#include <stdio.h>

static process_profile_definition* s_pc_profile_list[] = {
    &g_profile_OVERLAP0,
    &g_profile_OVERLAP1,
    &g_profile_OVERLAP3,
    &g_profile_OVERLAP6,
    &g_profile_OVERLAP7,
    &g_profile_OVERLAP8,
    &g_profile_OVERLAP9,
    &g_profile_OVERLAP10,
    &g_profile_OVERLAP11,
    &g_profile_LOGO_SCENE,
    &g_profile_MENU_SCENE,
    &g_profile_PLAY_SCENE,
    &g_profile_OPENING_SCENE,
    &g_profile_NAME_SCENE,
    &g_profile_NAMEEX_SCENE,
    &g_profile_WARNING_SCENE,
    &g_profile_WARNING2_SCENE,
    &g_profile_OVERLAP2,
    &g_profile_ROOM_SCENE,
    &g_profile_KANKYO,
    &g_profile_ALLDIE,
    &g_profile_ENVSE,
    NULL, /* g_profile_Obj_Swpush — REL module, not available */
    NULL, /* g_profile_Obj_Swpush2 — REL module, not available */
    NULL, /* g_profile_Obj_Swpush5 — REL module, not available */
    NULL, /* g_profile_Tag_Gstart — REL module, not available */
    NULL, /* g_profile_NO_CHG_ROOM — REL module, not available */
    NULL, /* g_profile_Obj_Lv6ElevtA — REL module, not available */
    NULL, /* g_profile_OBJ_SO — REL module, not available */
    NULL, /* g_profile_Obj_Movebox — REL module, not available */
    NULL, /* g_profile_Obj_SwTurn — REL module, not available */
    NULL, /* g_profile_Obj_Lv6SwTurn — REL module, not available */
    NULL, /* g_profile_OBJ_SEKIZOA — REL module, not available */
    NULL, /* g_profile_OBJ_GRA — REL module, not available */
    NULL, /* g_profile_TAG_GRA — REL module, not available */
    NULL, /* g_profile_TAG_YAMI — REL module, not available */
    NULL, /* g_profile_Obj_Ladder — REL module, not available */
    NULL, /* g_profile_OBJ_BEF — REL module, not available */
    NULL, /* g_profile_OBJ_FMOBJ — REL module, not available */
    NULL, /* g_profile_OBJ_LBOX — REL module, not available */
    NULL, /* g_profile_OBJ_WEB0 — REL module, not available */
    NULL, /* g_profile_OBJ_WEB1 — REL module, not available */
    NULL, /* g_profile_OBJ_CB — REL module, not available */
    NULL, /* g_profile_OBJ_MAKI — REL module, not available */
    NULL, /* g_profile_OBJ_BRG — REL module, not available */
    NULL, /* g_profile_OBJ_GB — REL module, not available */
    NULL, /* g_profile_OBJ_GM — REL module, not available */
    NULL, /* g_profile_OBJ_TOBY — REL module, not available */
    NULL, /* g_profile_OBJ_TP — REL module, not available */
    NULL, /* g_profile_TREESH — REL module, not available */
    NULL, /* g_profile_Obj_ZDoor — REL module, not available */
    NULL, /* g_profile_Obj_Pillar — REL module, not available */
    NULL, /* g_profile_Obj_Cdoor — REL module, not available */
    NULL, /* g_profile_GRDWATER — REL module, not available */
    NULL, /* g_profile_Obj_RotBridge — REL module, not available */
    NULL, /* g_profile_Obj_MagLift — REL module, not available */
    NULL, /* g_profile_Obj_MagLiftRot — REL module, not available */
    NULL, /* g_profile_Obj_Lv1Cdl00 — REL module, not available */
    NULL, /* g_profile_Obj_Lv1Cdl01 — REL module, not available */
    NULL, /* g_profile_Obj_TvCdlst — REL module, not available */
    NULL, /* g_profile_Obj_HsTarget — REL module, not available */
    NULL, /* g_profile_Obj_HeavySw — REL module, not available */
    NULL, /* g_profile_Obj_GoGate — REL module, not available */
    NULL, /* g_profile_Obj_TaFence — REL module, not available */
    NULL, /* g_profile_Obj_Saidan — REL module, not available */
    NULL, /* g_profile_Obj_SpinLift — REL module, not available */
    NULL, /* g_profile_Obj_BmWindow — REL module, not available */
    NULL, /* g_profile_Obj_RfHole — REL module, not available */
    NULL, /* g_profile_Obj_WaterPillar — REL module, not available */
    NULL, /* g_profile_Obj_SyRock — REL module, not available */
    NULL, /* g_profile_Obj_BsGate — REL module, not available */
    NULL, /* g_profile_Obj_AmiShutter — REL module, not available */
    NULL, /* g_profile_Obj_WtGate — REL module, not available */
    NULL, /* g_profile_Obj_Lv2Candle — REL module, not available */
    NULL, /* g_profile_Obj_TogeTrap — REL module, not available */
    NULL, /* g_profile_Obj_RotTrap — REL module, not available */
    NULL, /* g_profile_Obj_SwallShutter — REL module, not available */
    NULL, /* g_profile_Obj_IceWall — REL module, not available */
    NULL, /* g_profile_Obj_Lv5SwIce — REL module, not available */
    NULL, /* g_profile_Obj_Lv5FBoard — REL module, not available */
    NULL, /* g_profile_Obj_Turara — REL module, not available */
    NULL, /* g_profile_Obj_TwGate — REL module, not available */
    NULL, /* g_profile_Obj_Digholl — REL module, not available */
    NULL, /* g_profile_Obj_Digpl — REL module, not available */
    NULL, /* g_profile_Obj_TestCube — REL module, not available */
    NULL, /* g_profile_Obj_Kshutter — REL module, not available */
    NULL, /* g_profile_NPC_COACH — REL module, not available */
    NULL, /* g_profile_NPC_THEB — REL module, not available */
    NULL, /* g_profile_COACH_FIRE — REL module, not available */
    NULL, /* g_profile_COACH2D — REL module, not available */
    NULL, /* g_profile_BALLOON2D — REL module, not available */
    NULL, /* g_profile_SKIP2D — REL module, not available */
    NULL, /* g_profile_Obj_MvStair — REL module, not available */
    NULL, /* g_profile_Obj_Cowdoor — REL module, not available */
    NULL, /* g_profile_Obj_Swpropeller — REL module, not available */
    NULL, /* g_profile_Obj_BoomShutter — REL module, not available */
    NULL, /* g_profile_NPC_KS — REL module, not available */
    NULL, /* g_profile_Obj_Hfuta — REL module, not available */
    NULL, /* g_profile_Obj_BkDoor — REL module, not available */
    NULL, /* g_profile_Obj_Cboard — REL module, not available */
    NULL, /* g_profile_Obj_MGate — REL module, not available */
    &g_profile_Obj_Ikada,
    NULL, /* g_profile_Obj_Ice_l — REL module, not available */
    NULL, /* g_profile_Obj_Ice_s — REL module, not available */
    NULL, /* g_profile_Obj_E_CREATE — REL module, not available */
    NULL, /* g_profile_Obj_Bhbridge — REL module, not available */
    NULL, /* g_profile_Obj_Kaisou — REL module, not available */
    NULL, /* g_profile_Obj_HHASHI — REL module, not available */
    NULL, /* g_profile_Obj_BHASHI — REL module, not available */
    NULL, /* g_profile_OCTHASHI — REL module, not available */
    NULL, /* g_profile_Obj_THASHI — REL module, not available */
    NULL, /* g_profile_Obj_CRVGATE — REL module, not available */
    NULL, /* g_profile_Obj_CRVFENCE — REL module, not available */
    NULL, /* g_profile_Obj_CRVHAHEN — REL module, not available */
    NULL, /* g_profile_Obj_CRVSTEEL — REL module, not available */
    NULL, /* g_profile_Obj_CRVLH_UP — REL module, not available */
    NULL, /* g_profile_Obj_CRVLH_DW — REL module, not available */
    NULL, /* g_profile_Obj_RIVERROCK — REL module, not available */
    NULL, /* g_profile_Obj_DUST — REL module, not available */
    NULL, /* g_profile_Obj_ITA — REL module, not available */
    NULL, /* g_profile_Obj_Window — REL module, not available */
    NULL, /* g_profile_Obj_MetalBox — REL module, not available */
    NULL, /* g_profile_Obj_BBox — REL module, not available */
    NULL, /* g_profile_OBJ_MSIMA — REL module, not available */
    NULL, /* g_profile_OBJ_MYOGAN — REL module, not available */
    NULL, /* g_profile_B_ZANTS — REL module, not available */
    NULL, /* g_profile_Obj_ChainBlock — REL module, not available */
    NULL, /* g_profile_Obj_ChainWall — REL module, not available */
    NULL, /* g_profile_Obj_KkrGate — REL module, not available */
    NULL, /* g_profile_Obj_RiderGate — REL module, not available */
    NULL, /* g_profile_Obj_Onsen — REL module, not available */
    NULL, /* g_profile_Obj_Chest — REL module, not available */
    NULL, /* g_profile_Obj_Bemos — REL module, not available */
    NULL, /* g_profile_Obj_RopeBridge — REL module, not available */
    NULL, /* g_profile_Obj_WellCover — REL module, not available */
    NULL, /* g_profile_Obj_GraveStone — REL module, not available */
    NULL, /* g_profile_Obj_ZraRock — REL module, not available */
    NULL, /* g_profile_Obj_GraRock — REL module, not available */
    NULL, /* g_profile_Obj_GrzRock — REL module, not available */
    NULL, /* g_profile_GRA_WALL — REL module, not available */
    NULL, /* g_profile_OBJ_ONSEN_FIRE — REL module, not available */
    NULL, /* g_profile_Obj_Lv6bemos — REL module, not available */
    NULL, /* g_profile_Obj_Lv6bemos2 — REL module, not available */
    NULL, /* g_profile_Obj_BarDesk — REL module, not available */
    NULL, /* g_profile_Obj_DigSnow — REL module, not available */
    NULL, /* g_profile_Obj_Ytaihou — REL module, not available */
    NULL, /* g_profile_Obj_Elevator — REL module, not available */
    NULL, /* g_profile_Obj_Lv6TogeRoll — REL module, not available */
    NULL, /* g_profile_Obj_Lv6TogeTrap — REL module, not available */
    NULL, /* g_profile_Obj_Lv6Tenbin — REL module, not available */
    NULL, /* g_profile_Obj_Lv6SwGate — REL module, not available */
    NULL, /* g_profile_Obj_Lv6Lblock — REL module, not available */
    NULL, /* g_profile_Obj_Lv6ChgGate — REL module, not available */
    NULL, /* g_profile_Obj_Lv6FuriTrap — REL module, not available */
    NULL, /* g_profile_Obj_Lv6SzGate — REL module, not available */
    NULL, /* g_profile_Obj_Lv4EdShutter — REL module, not available */
    NULL, /* g_profile_Obj_Lv4Gate — REL module, not available */
    NULL, /* g_profile_Obj_Lv4PoGate — REL module, not available */
    NULL, /* g_profile_Obj_Lv4SlideWall — REL module, not available */
    NULL, /* g_profile_Obj_Lv4HsTarget — REL module, not available */
    NULL, /* g_profile_Obj_Lv7PropY — REL module, not available */
    NULL, /* g_profile_Obj_Lv7BsGate — REL module, not available */
    NULL, /* g_profile_Obj_Lv8OptiLift — REL module, not available */
    NULL, /* g_profile_Obj_Lv8KekkaiTrap — REL module, not available */
    NULL, /* g_profile_Obj_Lv8Lift — REL module, not available */
    NULL, /* g_profile_Obj_Lv8UdFloor — REL module, not available */
    NULL, /* g_profile_Obj_Lv9SwShutter — REL module, not available */
    NULL, /* g_profile_Obj_TobyHouse — REL module, not available */
    NULL, /* g_profile_Obj_poCandle — REL module, not available */
    NULL, /* g_profile_Obj_Lv4DigSand — REL module, not available */
    NULL, /* g_profile_Obj_FallObj — REL module, not available */
    NULL, /* g_profile_Obj_SmgDoor — REL module, not available */
    NULL, /* g_profile_Obj_SwLight — REL module, not available */
    NULL, /* g_profile_Obj_Avalanche — REL module, not available */
    NULL, /* g_profile_Obj_MirrorScrew — REL module, not available */
    NULL, /* g_profile_Obj_MirrorSand — REL module, not available */
    NULL, /* g_profile_Obj_MirrorTable — REL module, not available */
    NULL, /* g_profile_Obj_MirrorChain — REL module, not available */
    NULL, /* g_profile_Obj_Mirror6Pole — REL module, not available */
    NULL, /* g_profile_Obj_SwSpinner — REL module, not available */
    NULL, /* g_profile_Obj_TDoor — REL module, not available */
    NULL, /* g_profile_Obj_Lv7Bridge — REL module, not available */
    NULL, /* g_profile_Obj_zrTurara — REL module, not available */
    NULL, /* g_profile_Obj_TakaraDai — REL module, not available */
    NULL, /* g_profile_Obj_Table — REL module, not available */
    NULL, /* g_profile_Obj_CatDoor — REL module, not available */
    NULL, /* g_profile_Obj_Gake — REL module, not available */
    NULL, /* g_profile_CSTAF — REL module, not available */
    NULL, /* g_profile_Obj_Lv4RailWall — REL module, not available */
    NULL, /* g_profile_Obj_Lv4Sand — REL module, not available */
    NULL, /* g_profile_Obj_PushDoor — REL module, not available */
    NULL, /* g_profile_PushDoor — REL module, not available */
    NULL, /* g_profile_Obj_GanonWall2 — REL module, not available */
    NULL, /* g_profile_Obj_Lv4Bridge — REL module, not available */
    NULL, /* g_profile_Obj_Lv4Floor — REL module, not available */
    NULL, /* g_profile_Tag_Spinner — REL module, not available */
    NULL, /* g_profile_Obj_SwHang — REL module, not available */
    NULL, /* g_profile_Obj_RotStair — REL module, not available */
    NULL, /* g_profile_Obj_MagneArm — REL module, not available */
    NULL, /* g_profile_Obj_KWheel00 — REL module, not available */
    NULL, /* g_profile_Obj_KWheel01 — REL module, not available */
    NULL, /* g_profile_Obj_Ychndlr — REL module, not available */
    NULL, /* g_profile_Obj_PRElvtr — REL module, not available */
    NULL, /* g_profile_Obj_MHasu — REL module, not available */
    NULL, /* g_profile_Obj_YIblltray — REL module, not available */
    NULL, /* g_profile_Obj_Lv6EGate — REL module, not available */
    NULL, /* g_profile_Obj_PDtile — REL module, not available */
    NULL, /* g_profile_Obj_PDwall — REL module, not available */
    NULL, /* g_profile_Obj_Lv4PRwall — REL module, not available */
    NULL, /* g_profile_Obj_KLift00 — REL module, not available */
    NULL, /* g_profile_B_OH — REL module, not available */
    NULL, /* g_profile_Obj_Lv4Chan — REL module, not available */
    NULL, /* g_profile_Obj_Lv3R10Saka — REL module, not available */
    NULL, /* g_profile_Obj_Lv3Water — REL module, not available */
    NULL, /* g_profile_Obj_Lv3Water2 — REL module, not available */
    NULL, /* g_profile_OBJ_LV3WATERB — REL module, not available */
    NULL, /* g_profile_Obj_HBombkoya — REL module, not available */
    NULL, /* g_profile_Obj_SZbridge — REL module, not available */
    NULL, /* g_profile_Obj_KakarikoBrg — REL module, not available */
    NULL, /* g_profile_Obj_OrdinBrg — REL module, not available */
    NULL, /* g_profile_Obj_BurnBox — REL module, not available */
    NULL, /* g_profile_Obj_KJgjs — REL module, not available */
    NULL, /* g_profile_OBJ_IHASI — REL module, not available */
    NULL, /* g_profile_Obj_IceBlock — REL module, not available */
    NULL, /* g_profile_Obj_VolcanicBall — REL module, not available */
    NULL, /* g_profile_Obj_VolcanicBomb — REL module, not available */
    NULL, /* g_profile_Obj_VolcGnd — REL module, not available */
    NULL, /* g_profile_Obj_KKanban — REL module, not available */
    NULL, /* g_profile_E_PH — REL module, not available */
    NULL, /* g_profile_NPC_ZRA — REL module, not available */
    NULL, /* g_profile_Obj_Chandelier — REL module, not available */
    NULL, /* g_profile_Obj_Stopper2 — REL module, not available */
    NULL, /* g_profile_DOOR20 — REL module, not available */
    NULL, /* g_profile_Tag_Hinit — REL module, not available */
    NULL, /* g_profile_Tag_Hjump — REL module, not available */
    NULL, /* g_profile_Tag_AJnot — REL module, not available */
    NULL, /* g_profile_Tag_Hstop — REL module, not available */
    NULL, /* g_profile_CANOE — REL module, not available */
    NULL, /* g_profile_HORSE — REL module, not available */
    NULL, /* g_profile_E_WB — REL module, not available */
    NULL, /* g_profile_OBJ_ITO — REL module, not available */
    NULL, /* g_profile_OBJ_SW — REL module, not available */
    NULL, /* g_profile_SPINNER — REL module, not available */
    NULL, /* g_profile_B_OB — REL module, not available */
    NULL, /* g_profile_KAGO — REL module, not available */
    NULL, /* g_profile_E_YC — REL module, not available */
    NULL, /* g_profile_B_DS — REL module, not available */
    NULL, /* g_profile_B_DR — REL module, not available */
    NULL, /* g_profile_B_ZANTZ — REL module, not available */
    NULL, /* g_profile_B_ZANT — REL module, not available */
    NULL, /* g_profile_B_ZANTM — REL module, not available */
    NULL, /* g_profile_TBOX — REL module, not available */
    NULL, /* g_profile_TBOX2 — REL module, not available */
    &g_profile_ALINK,
    NULL, /* g_profile_BOOMERANG — REL module, not available */
    NULL, /* g_profile_MIDNA — REL module, not available */
    NULL, /* g_profile_NPC_TK — REL module, not available */
    NULL, /* g_profile_NPC_WORM — REL module, not available */
    NULL, /* g_profile_PPolamp — REL module, not available */
    NULL, /* g_profile_BkyRock — REL module, not available */
    NULL, /* g_profile_HITOBJ — REL module, not available */
    NULL, /* g_profile_EP — REL module, not available */
    NULL, /* g_profile_COW — REL module, not available */
    NULL, /* g_profile_PERU — REL module, not available */
    NULL, /* g_profile_NI — REL module, not available */
    NULL, /* g_profile_NPC_TKJ2 — REL module, not available */
    NULL, /* g_profile_SQ — REL module, not available */
    NULL, /* g_profile_NPC_SQ — REL module, not available */
    NULL, /* g_profile_DO — REL module, not available */
    NULL, /* g_profile_NPC_NE — REL module, not available */
    NULL, /* g_profile_NPC_TR — REL module, not available */
    NULL, /* g_profile_NPC_LF — REL module, not available */
    NULL, /* g_profile_OBJ_FOOD — REL module, not available */
    NULL, /* g_profile_OBJ_KI — REL module, not available */
    NULL, /* g_profile_OBJ_KITA — REL module, not available */
    NULL, /* g_profile_OBJ_KEY — REL module, not available */
    NULL, /* g_profile_OBJ_KEYHOLE — REL module, not available */
    NULL, /* g_profile_Obj_Lv5Key — REL module, not available */
    NULL, /* g_profile_OBJ_LP — REL module, not available */
    NULL, /* g_profile_OBJ_TATIGI — REL module, not available */
    NULL, /* g_profile_OBJ_ROCK — REL module, not available */
    NULL, /* g_profile_OBJ_WFLAG — REL module, not available */
    NULL, /* g_profile_OBJ_KAGE — REL module, not available */
    NULL, /* g_profile_OBJ_KANBAN2 — REL module, not available */
    NULL, /* g_profile_OBJ_BALLOON — REL module, not available */
    NULL, /* g_profile_OBJ_SUISYA — REL module, not available */
    NULL, /* g_profile_OBJ_OILTUBO — REL module, not available */
    NULL, /* g_profile_OBJ_ROTEN — REL module, not available */
    NULL, /* g_profile_OBJ_SSDRINK — REL module, not available */
    NULL, /* g_profile_OBJ_SSITEM — REL module, not available */
    NULL, /* g_profile_TAG_SSDRINK — REL module, not available */
    NULL, /* g_profile_TAG_BTLITM — REL module, not available */
    NULL, /* g_profile_TAG_LV5SOUP — REL module, not available */
    NULL, /* g_profile_TAG_MNLIGHT — REL module, not available */
    NULL, /* g_profile_TAG_SHOPCAM — REL module, not available */
    NULL, /* g_profile_TAG_SHOPITM — REL module, not available */
    NULL, /* g_profile_OBJ_NDOOR — REL module, not available */
    NULL, /* g_profile_OBJ_UDOOR — REL module, not available */
    NULL, /* g_profile_OBJ_USAKU — REL module, not available */
    NULL, /* g_profile_Obj_SM_DOOR — REL module, not available */
    NULL, /* g_profile_OBJ_BED — REL module, not available */
    NULL, /* g_profile_OBJ_BOUMATO — REL module, not available */
    NULL, /* g_profile_OBJ_ITAMATO — REL module, not available */
    NULL, /* g_profile_OBJ_NOUGU — REL module, not available */
    NULL, /* g_profile_OBJ_STICK — REL module, not available */
    NULL, /* g_profile_OBJ_MIE — REL module, not available */
    NULL, /* g_profile_OBJ_SEKIDOOR — REL module, not available */
    NULL, /* g_profile_OBJ_SEKIZO — REL module, not available */
    NULL, /* g_profile_OBJ_SMTILE — REL module, not available */
    NULL, /* g_profile_NPC_FISH — REL module, not available */
    NULL, /* g_profile_MG_FISH — REL module, not available */
    NULL, /* g_profile_FSHOP — REL module, not available */
    NULL, /* g_profile_NPC_DU — REL module, not available */
    NULL, /* g_profile_DISAPPEAR — REL module, not available */
    NULL, /* g_profile_Obj_Mato — REL module, not available */
    NULL, /* g_profile_Obj_Flag — REL module, not available */
    NULL, /* g_profile_Obj_Flag2 — REL module, not available */
    NULL, /* g_profile_Obj_Flag3 — REL module, not available */
    NULL, /* g_profile_Obj_GOMIKABE — REL module, not available */
    NULL, /* g_profile_Obj_Yousei — REL module, not available */
    NULL, /* g_profile_Obj_Kabuto — REL module, not available */
    NULL, /* g_profile_Obj_Cho — REL module, not available */
    NULL, /* g_profile_Obj_Kuw — REL module, not available */
    NULL, /* g_profile_Obj_Nan — REL module, not available */
    NULL, /* g_profile_Obj_Dan — REL module, not available */
    NULL, /* g_profile_Obj_Kam — REL module, not available */
    NULL, /* g_profile_Obj_Ten — REL module, not available */
    NULL, /* g_profile_Obj_Ari — REL module, not available */
    NULL, /* g_profile_Obj_Kag — REL module, not available */
    NULL, /* g_profile_Obj_Batta — REL module, not available */
    NULL, /* g_profile_Obj_Tombo — REL module, not available */
    NULL, /* g_profile_Obj_Kat — REL module, not available */
    NULL, /* g_profile_Obj_H_Saku — REL module, not available */
    NULL, /* g_profile_Obj_Yobikusa — REL module, not available */
    NULL, /* g_profile_Obj_KazeNeko — REL module, not available */
    NULL, /* g_profile_Obj_KznkArm — REL module, not available */
    NULL, /* g_profile_Obj_NamePlate — REL module, not available */
    NULL, /* g_profile_Obj_OnCloth — REL module, not available */
    NULL, /* g_profile_Obj_LndRope — REL module, not available */
    NULL, /* g_profile_Obj_ItaRope — REL module, not available */
    NULL, /* g_profile_Obj_Sakuita — REL module, not available */
    NULL, /* g_profile_Obj_Laundry — REL module, not available */
    NULL, /* g_profile_WarpBug — REL module, not available */
    NULL, /* g_profile_Izumi_Gate — REL module, not available */
    NULL, /* g_profile_Obj_Fchain — REL module, not available */
    NULL, /* g_profile_Obj_Wchain — REL module, not available */
    NULL, /* g_profile_Tag_Attp — REL module, not available */
    NULL, /* g_profile_Obj_Tornado — REL module, not available */
    NULL, /* g_profile_Obj_Tornado2 — REL module, not available */
    NULL, /* g_profile_Obj_FirePillar — REL module, not available */
    NULL, /* g_profile_Obj_FirePillar2 — REL module, not available */
    NULL, /* g_profile_Obj_InoBone — REL module, not available */
    NULL, /* g_profile_Obj_Stopper — REL module, not available */
    NULL, /* g_profile_Obj_MHole — REL module, not available */
    NULL, /* g_profile_Tag_Magne — REL module, not available */
    NULL, /* g_profile_Obj_BossWarp — REL module, not available */
    NULL, /* g_profile_Obj_WoodPendulum — REL module, not available */
    NULL, /* g_profile_Obj_WdStick — REL module, not available */
    NULL, /* g_profile_Obj_StairBlock — REL module, not available */
    NULL, /* g_profile_Obj_Geyser — REL module, not available */
    NULL, /* g_profile_Tag_KtOnFire — REL module, not available */
    NULL, /* g_profile_Obj_FireWood — REL module, not available */
    NULL, /* g_profile_Obj_FireWood2 — REL module, not available */
    NULL, /* g_profile_Obj_GpTaru — REL module, not available */
    NULL, /* g_profile_Obj_OnsenTaru — REL module, not available */
    NULL, /* g_profile_Obj_KiPot — REL module, not available */
    NULL, /* g_profile_TBOX_SW — REL module, not available */
    NULL, /* g_profile_Obj_SwChain — REL module, not available */
    NULL, /* g_profile_Obj_WoodenSword — REL module, not available */
    NULL, /* g_profile_Obj_StoneMark — REL module, not available */
    NULL, /* g_profile_Obj_Lv3Candle — REL module, not available */
    NULL, /* g_profile_Tag_Lv4Candle — REL module, not available */
    NULL, /* g_profile_Tag_Lv4CandleDm — REL module, not available */
    NULL, /* g_profile_Obj_DamCps — REL module, not available */
    NULL, /* g_profile_Obj_Smoke — REL module, not available */
    NULL, /* g_profile_Obj_WaterFall — REL module, not available */
    NULL, /* g_profile_Obj_ZoraCloth — REL module, not available */
    NULL, /* g_profile_Obj_poFire — REL module, not available */
    NULL, /* g_profile_Tag_poFire — REL module, not available */
    NULL, /* g_profile_Obj_glowSphere — REL module, not available */
    NULL, /* g_profile_Tag_LightBall — REL module, not available */
    NULL, /* g_profile_SwLBall — REL module, not available */
    NULL, /* g_profile_SwBall — REL module, not available */
    NULL, /* g_profile_Obj_WaterEff — REL module, not available */
    NULL, /* g_profile_Tag_RiverBack — REL module, not available */
    NULL, /* g_profile_Tag_KagoFall — REL module, not available */
    NULL, /* g_profile_Tag_Lv2PrChk — REL module, not available */
    NULL, /* g_profile_Obj_Lv4Gear — REL module, not available */
    NULL, /* g_profile_Obj_MasterSword — REL module, not available */
    NULL, /* g_profile_Obj_WoodStatue — REL module, not available */
    NULL, /* g_profile_Obj_Fan — REL module, not available */
    NULL, /* g_profile_Obj_IceLeaf — REL module, not available */
    NULL, /* g_profile_Obj_zrTuraraRc — REL module, not available */
    NULL, /* g_profile_Tag_RetRoom — REL module, not available */
    NULL, /* g_profile_Obj_WindStone — REL module, not available */
    NULL, /* g_profile_Tag_WaraHowl — REL module, not available */
    NULL, /* g_profile_Obj_SCannon — REL module, not available */
    NULL, /* g_profile_Obj_SmWStone — REL module, not available */
    NULL, /* g_profile_Obj_SCannonCrs — REL module, not available */
    NULL, /* g_profile_Tag_SnowEff — REL module, not available */
    NULL, /* g_profile_Tag_CstaSw — REL module, not available */
    NULL, /* g_profile_Tag_Lv6CstaSw — REL module, not available */
    NULL, /* g_profile_Obj_awaPlar — REL module, not available */
    NULL, /* g_profile_Obj_poTbox — REL module, not available */
    NULL, /* g_profile_Obj_TimeFire — REL module, not available */
    NULL, /* g_profile_Obj_TMoon — REL module, not available */
    NULL, /* g_profile_Obj_GanonWall — REL module, not available */
    NULL, /* g_profile_Obj_Prop — REL module, not available */
    NULL, /* g_profile_CSTATUE — REL module, not available */
    NULL, /* g_profile_Obj_SwBallA — REL module, not available */
    NULL, /* g_profile_Obj_SwBallB — REL module, not available */
    NULL, /* g_profile_Obj_SnowSoup — REL module, not available */
    NULL, /* g_profile_Obj_Nagaisu — REL module, not available */
    NULL, /* g_profile_Obj_RCircle — REL module, not available */
    NULL, /* g_profile_Obj_Picture — REL module, not available */
    NULL, /* g_profile_Tag_SetBall — REL module, not available */
    NULL, /* g_profile_Tag_SmkEmt — REL module, not available */
    NULL, /* g_profile_SwTime — REL module, not available */
    NULL, /* g_profile_Obj_HFtr — REL module, not available */
    NULL, /* g_profile_Obj_HBarrel — REL module, not available */
    NULL, /* g_profile_Obj_Crystal — REL module, not available */
    NULL, /* g_profile_Obj_SCannonTen — REL module, not available */
    NULL, /* g_profile_Obj_SwBallC — REL module, not available */
    NULL, /* g_profile_SCENE_EXIT2 — REL module, not available */
    NULL, /* g_profile_Obj_Hata — REL module, not available */
    NULL, /* g_profile_Obj_ToaruMaki — REL module, not available */
    NULL, /* g_profile_Tag_AttackItem — REL module, not available */
    NULL, /* g_profile_Tag_RmbitSw — REL module, not available */
    NULL, /* g_profile_Obj_Sword — REL module, not available */
    NULL, /* g_profile_Tag_Spring — REL module, not available */
    NULL, /* g_profile_Tag_Statue — REL module, not available */
    NULL, /* g_profile_E_AI — REL module, not available */
    NULL, /* g_profile_E_GS — REL module, not available */
    NULL, /* g_profile_E_GOB — REL module, not available */
    NULL, /* g_profile_E_DD — REL module, not available */
    NULL, /* g_profile_E_DN — REL module, not available */
    NULL, /* g_profile_E_S1 — REL module, not available */
    NULL, /* g_profile_E_MF — REL module, not available */
    NULL, /* g_profile_E_SG — REL module, not available */
    NULL, /* g_profile_E_BS — REL module, not available */
    NULL, /* g_profile_E_SF — REL module, not available */
    NULL, /* g_profile_E_SH — REL module, not available */
    NULL, /* g_profile_E_DF — REL module, not available */
    NULL, /* g_profile_E_GM — REL module, not available */
    NULL, /* g_profile_E_MD — REL module, not available */
    NULL, /* g_profile_E_SM — REL module, not available */
    NULL, /* g_profile_E_SM2 — REL module, not available */
    NULL, /* g_profile_E_ST — REL module, not available */
    NULL, /* g_profile_E_ST_LINE — REL module, not available */
    NULL, /* g_profile_E_SB — REL module, not available */
    NULL, /* g_profile_E_TH — REL module, not available */
    NULL, /* g_profile_E_CR — REL module, not available */
    NULL, /* g_profile_E_CR_EGG — REL module, not available */
    NULL, /* g_profile_E_DB — REL module, not available */
    NULL, /* g_profile_E_DB_LEAF — REL module, not available */
    NULL, /* g_profile_E_GA — REL module, not available */
    NULL, /* g_profile_E_GB — REL module, not available */
    NULL, /* g_profile_E_HB — REL module, not available */
    NULL, /* g_profile_E_HB_LEAF — REL module, not available */
    NULL, /* g_profile_E_HZELDA — REL module, not available */
    NULL, /* g_profile_E_YD — REL module, not available */
    NULL, /* g_profile_E_YH — REL module, not available */
    NULL, /* g_profile_E_YD_LEAF — REL module, not available */
    NULL, /* g_profile_E_HM — REL module, not available */
    NULL, /* g_profile_E_TK — REL module, not available */
    NULL, /* g_profile_E_TK2 — REL module, not available */
    NULL, /* g_profile_E_TK_BALL — REL module, not available */
    NULL, /* g_profile_E_RB — REL module, not available */
    NULL, /* g_profile_E_RD — REL module, not available */
    NULL, /* g_profile_E_RDB — REL module, not available */
    NULL, /* g_profile_E_RDY — REL module, not available */
    NULL, /* g_profile_E_FM — REL module, not available */
    NULL, /* g_profile_E_FS — REL module, not available */
    NULL, /* g_profile_E_PM — REL module, not available */
    NULL, /* g_profile_E_PO — REL module, not available */
    NULL, /* g_profile_E_MB — REL module, not available */
    NULL, /* g_profile_E_MK — REL module, not available */
    NULL, /* g_profile_E_MM — REL module, not available */
    NULL, /* g_profile_E_FZ — REL module, not available */
    NULL, /* g_profile_E_ZS — REL module, not available */
    NULL, /* g_profile_E_KK — REL module, not available */
    NULL, /* g_profile_E_HP — REL module, not available */
    NULL, /* g_profile_E_ZH — REL module, not available */
    NULL, /* g_profile_E_ZM — REL module, not available */
    NULL, /* g_profile_E_PZ — REL module, not available */
    NULL, /* g_profile_E_FB — REL module, not available */
    NULL, /* g_profile_E_FK — REL module, not available */
    NULL, /* g_profile_E_MS — REL module, not available */
    NULL, /* g_profile_E_NEST — REL module, not available */
    NULL, /* g_profile_E_NZ — REL module, not available */
    NULL, /* g_profile_E_BA — REL module, not available */
    NULL, /* g_profile_E_BU — REL module, not available */
    NULL, /* g_profile_E_BUG — REL module, not available */
    NULL, /* g_profile_E_BEE — REL module, not available */
    NULL, /* g_profile_E_IS — REL module, not available */
    NULL, /* g_profile_E_KG — REL module, not available */
    NULL, /* g_profile_E_KR — REL module, not available */
    NULL, /* g_profile_E_SW — REL module, not available */
    NULL, /* g_profile_E_GE — REL module, not available */
    NULL, /* g_profile_Tag_WatchGe — REL module, not available */
    NULL, /* g_profile_E_YM — REL module, not available */
    NULL, /* g_profile_E_YM_TAG — REL module, not available */
    NULL, /* g_profile_E_YMB — REL module, not available */
    NULL, /* g_profile_Tag_FWall — REL module, not available */
    NULL, /* g_profile_Tag_WaterFall — REL module, not available */
    NULL, /* g_profile_E_YK — REL module, not available */
    NULL, /* g_profile_E_YR — REL module, not available */
    NULL, /* g_profile_E_YG — REL module, not available */
    NULL, /* g_profile_E_HZ — REL module, not available */
    NULL, /* g_profile_E_WS — REL module, not available */
    NULL, /* g_profile_E_OC — REL module, not available */
    NULL, /* g_profile_E_OT — REL module, not available */
    NULL, /* g_profile_E_DT — REL module, not available */
    NULL, /* g_profile_E_BG — REL module, not available */
    NULL, /* g_profile_E_OctBg — REL module, not available */
    NULL, /* g_profile_DR — REL module, not available */
    NULL, /* g_profile_L7lowDr — REL module, not available */
    NULL, /* g_profile_L7ODR — REL module, not available */
    NULL, /* g_profile_E_TT — REL module, not available */
    NULL, /* g_profile_E_DK — REL module, not available */
    NULL, /* g_profile_E_VT — REL module, not available */
    NULL, /* g_profile_E_WW — REL module, not available */
    NULL, /* g_profile_E_GI — REL module, not available */
    NULL, /* g_profile_B_BH — REL module, not available */
    NULL, /* g_profile_B_BQ — REL module, not available */
    NULL, /* g_profile_B_GM — REL module, not available */
    NULL, /* g_profile_B_GND — REL module, not available */
    NULL, /* g_profile_B_GO — REL module, not available */
    NULL, /* g_profile_B_OH2 — REL module, not available */
    NULL, /* g_profile_B_YO — REL module, not available */
    NULL, /* g_profile_B_YOI — REL module, not available */
    NULL, /* g_profile_B_TN — REL module, not available */
    NULL, /* g_profile_B_GG — REL module, not available */
    NULL, /* g_profile_B_DRE — REL module, not available */
    NULL, /* g_profile_B_MGN — REL module, not available */
    NULL, /* g_profile_E_WAP — REL module, not available */
    &g_profile_ITEM,
    NULL, /* g_profile_Obj_SmallKey — REL module, not available */
    NULL, /* g_profile_Obj_Kantera — REL module, not available */
    NULL, /* g_profile_Obj_LifeContainer — REL module, not available */
    NULL, /* g_profile_Obj_Shield — REL module, not available */
    NULL, /* g_profile_Demo_Item — REL module, not available */
    &g_profile_ShopItem,
    NULL, /* g_profile_Obj_Drop — REL module, not available */
    NULL, /* g_profile_OBJ_RW — REL module, not available */
    NULL, /* g_profile_NBOMB — REL module, not available */
    NULL, /* g_profile_TAG_CSW — REL module, not available */
    NULL, /* g_profile_TAG_QS — REL module, not available */
    NULL, /* g_profile_HOZELDA — REL module, not available */
    &g_profile_SWC00,
    NULL, /* g_profile_KNOB20 — REL module, not available */
    NULL, /* g_profile_DBDOOR — REL module, not available */
    NULL, /* g_profile_BOSS_DOOR — REL module, not available */
    NULL, /* g_profile_L1BOSS_DOOR — REL module, not available */
    NULL, /* g_profile_L1MBOSS_DOOR — REL module, not available */
    NULL, /* g_profile_L5BOSS_DOOR — REL module, not available */
    NULL, /* g_profile_DSHUTTER — REL module, not available */
    NULL, /* g_profile_SPIRAL_DOOR — REL module, not available */
    NULL, /* g_profile_Tag_ChgRestart — REL module, not available */
    NULL, /* g_profile_Tag_Restart — REL module, not available */
    NULL, /* g_profile_ANDSW — REL module, not available */
    &g_profile_ANDSW2,
    NULL, /* g_profile_MYNA — REL module, not available */
    NULL, /* g_profile_NPC_GND — REL module, not available */
    NULL, /* g_profile_NPC_GRA — REL module, not available */
    NULL, /* g_profile_NPC_GRC — REL module, not available */
    NULL, /* g_profile_NPC_GRD — REL module, not available */
    NULL, /* g_profile_NPC_GRM — REL module, not available */
    NULL, /* g_profile_NPC_GRMC — REL module, not available */
    NULL, /* g_profile_NPC_GRO — REL module, not available */
    NULL, /* g_profile_NPC_GRR — REL module, not available */
    NULL, /* g_profile_NPC_GRS — REL module, not available */
    NULL, /* g_profile_NPC_GRZ — REL module, not available */
    NULL, /* g_profile_NPC_YAMID — REL module, not available */
    NULL, /* g_profile_NPC_YAMIT — REL module, not available */
    NULL, /* g_profile_NPC_YAMIS — REL module, not available */
    NULL, /* g_profile_NPC_BLUENS — REL module, not available */
    NULL, /* g_profile_NPC_KAKASHI — REL module, not available */
    NULL, /* g_profile_NPC_KDK — REL module, not available */
    NULL, /* g_profile_NPC_ARU — REL module, not available */
    NULL, /* g_profile_NPC_BANS — REL module, not available */
    NULL, /* g_profile_NPC_BESU — REL module, not available */
    NULL, /* g_profile_NPC_BOU — REL module, not available */
    NULL, /* g_profile_NPC_BOU_S — REL module, not available */
    NULL, /* g_profile_NPC_CLERKA — REL module, not available */
    NULL, /* g_profile_NPC_CLERKB — REL module, not available */
    NULL, /* g_profile_NPC_CLERKT — REL module, not available */
    NULL, /* g_profile_NPC_WRESTLER — REL module, not available */
    NULL, /* g_profile_Tag_Arena — REL module, not available */
    NULL, /* g_profile_Tag_Instruction — REL module, not available */
    NULL, /* g_profile_NPC_DOC — REL module, not available */
    NULL, /* g_profile_NPC_GWOLF — REL module, not available */
    NULL, /* g_profile_NPC_LEN — REL module, not available */
    NULL, /* g_profile_NPC_LUD — REL module, not available */
    NULL, /* g_profile_NPC_FAIRY_SEIREI — REL module, not available */
    NULL, /* g_profile_NPC_FAIRY — REL module, not available */
    NULL, /* g_profile_NPC_HANJO — REL module, not available */
    NULL, /* g_profile_NPC_HENNA — REL module, not available */
    NULL, /* g_profile_NPC_HENNA0 — REL module, not available */
    NULL, /* g_profile_NPC_HOZ — REL module, not available */
    NULL, /* g_profile_NPC_JAGAR — REL module, not available */
    NULL, /* g_profile_NPC_KKRI — REL module, not available */
    NULL, /* g_profile_NPC_KN — REL module, not available */
    NULL, /* g_profile_KN_BULLET — REL module, not available */
    NULL, /* g_profile_NPC_KNJ — REL module, not available */
    NULL, /* g_profile_NPC_KOLIN — REL module, not available */
    NULL, /* g_profile_NPC_KOLINB — REL module, not available */
    NULL, /* g_profile_NPC_KYURY — REL module, not available */
    NULL, /* g_profile_NPC_MARO — REL module, not available */
    NULL, /* g_profile_NPC_MIDP — REL module, not available */
    NULL, /* g_profile_NPC_MOI — REL module, not available */
    NULL, /* g_profile_NPC_RACA — REL module, not available */
    NULL, /* g_profile_NPC_SARU — REL module, not available */
    NULL, /* g_profile_NPC_SEIB — REL module, not available */
    NULL, /* g_profile_NPC_SEIC — REL module, not available */
    NULL, /* g_profile_NPC_SEID — REL module, not available */
    NULL, /* g_profile_NPC_SEIRA — REL module, not available */
    NULL, /* g_profile_NPC_SERA2 — REL module, not available */
    NULL, /* g_profile_NPC_SEIREI — REL module, not available */
    NULL, /* g_profile_NPC_SHAMAN — REL module, not available */
    NULL, /* g_profile_NPC_SMARO — REL module, not available */
    NULL, /* g_profile_NPC_SOLA — REL module, not available */
    NULL, /* g_profile_NPC_TARO — REL module, not available */
    NULL, /* g_profile_NPC_PACHI_BESU — REL module, not available */
    NULL, /* g_profile_NPC_PACHI_TARO — REL module, not available */
    NULL, /* g_profile_NPC_PACHI_MARO — REL module, not available */
    NULL, /* g_profile_TAG_PATI — REL module, not available */
    NULL, /* g_profile_NPC_THE — REL module, not available */
    NULL, /* g_profile_NPC_TKJ — REL module, not available */
    NULL, /* g_profile_NPC_TKS — REL module, not available */
    NULL, /* g_profile_NPC_TKC — REL module, not available */
    NULL, /* g_profile_OBJ_TKS — REL module, not available */
    NULL, /* g_profile_NPC_TOBY — REL module, not available */
    NULL, /* g_profile_NPC_URI — REL module, not available */
    NULL, /* g_profile_NPC_YELIA — REL module, not available */
    NULL, /* g_profile_NPC_YKM — REL module, not available */
    NULL, /* g_profile_NPC_YKW — REL module, not available */
    NULL, /* g_profile_NPC_ZANB — REL module, not available */
    NULL, /* g_profile_NPC_ZANT — REL module, not available */
    NULL, /* g_profile_NPC_ZELDA — REL module, not available */
    NULL, /* g_profile_NPC_ZELR — REL module, not available */
    NULL, /* g_profile_NPC_ZELRO — REL module, not available */
    NULL, /* g_profile_OBJ_ZRAFREEZE — REL module, not available */
    NULL, /* g_profile_NPC_ZRC — REL module, not available */
    NULL, /* g_profile_NPC_ZRZ — REL module, not available */
    NULL, /* g_profile_ZRA_MARK — REL module, not available */
    NULL, /* g_profile_MYNA2 — REL module, not available */
    NULL, /* g_profile_TAG_MYNA2 — REL module, not available */
    NULL, /* g_profile_NPC_CD3 — REL module, not available */
    NULL, /* g_profile_Tag_Schedule — REL module, not available */
    NULL, /* g_profile_Tag_Escape — REL module, not available */
    NULL, /* g_profile_NPC_CHAT — REL module, not available */
    NULL, /* g_profile_NPC_SOLDIERa — REL module, not available */
    NULL, /* g_profile_NPC_SOLDIERb — REL module, not available */
    NULL, /* g_profile_PASSER_MNG — REL module, not available */
    NULL, /* g_profile_NPC_PASSER — REL module, not available */
    NULL, /* g_profile_NPC_PASSER2 — REL module, not available */
    NULL, /* g_profile_NPC_POST — REL module, not available */
    NULL, /* g_profile_NPC_POUYA — REL module, not available */
    NULL, /* g_profile_FORMATION_MNG — REL module, not available */
    NULL, /* g_profile_NPC_FGUARD — REL module, not available */
    NULL, /* g_profile_GUARD_MNG — REL module, not available */
    NULL, /* g_profile_TAG_GUARD — REL module, not available */
    NULL, /* g_profile_NPC_GUARD — REL module, not available */
    NULL, /* g_profile_NPC_ASH — REL module, not available */
    NULL, /* g_profile_NPC_ASHB — REL module, not available */
    NULL, /* g_profile_NPC_SHAD — REL module, not available */
    NULL, /* g_profile_NPC_RAFREL — REL module, not available */
    NULL, /* g_profile_NPC_MOIR — REL module, not available */
    NULL, /* g_profile_NPC_IMPAL — REL module, not available */
    NULL, /* g_profile_NPC_SHOE — REL module, not available */
    NULL, /* g_profile_NPC_DOORBOY — REL module, not available */
    NULL, /* g_profile_NPC_PRAYER — REL module, not available */
    NULL, /* g_profile_NPC_KASIHANA — REL module, not available */
    NULL, /* g_profile_NPC_KASIKYU — REL module, not available */
    NULL, /* g_profile_NPC_KASIMICH — REL module, not available */
    NULL, /* g_profile_NPC_DRSOL — REL module, not available */
    NULL, /* g_profile_NPC_CHIN — REL module, not available */
    NULL, /* g_profile_NPC_INS — REL module, not available */
    NULL, /* g_profile_NPC_SHOP0 — REL module, not available */
    &g_profile_NPC_MK,
    NULL, /* g_profile_NPC_P2 — REL module, not available */
    NULL, /* g_profile_KYTAG00 — REL module, not available */
    &g_profile_KYTAG01,
    NULL, /* g_profile_KYTAG02 — REL module, not available */
    NULL, /* g_profile_KYTAG03 — REL module, not available */
    NULL, /* g_profile_KYTAG04 — REL module, not available */
    NULL, /* g_profile_KYTAG05 — REL module, not available */
    NULL, /* g_profile_KYTAG06 — REL module, not available */
    NULL, /* g_profile_KYTAG07 — REL module, not available */
    NULL, /* g_profile_KYTAG08 — REL module, not available */
    NULL, /* g_profile_KYTAG09 — REL module, not available */
    NULL, /* g_profile_KYTAG10 — REL module, not available */
    NULL, /* g_profile_KYTAG11 — REL module, not available */
    NULL, /* g_profile_KYTAG12 — REL module, not available */
    NULL, /* g_profile_KYTAG13 — REL module, not available */
    NULL, /* g_profile_KYTAG14 — REL module, not available */
    NULL, /* g_profile_KYTAG15 — REL module, not available */
    NULL, /* g_profile_KYTAG16 — REL module, not available */
    NULL, /* g_profile_KYTAG17 — REL module, not available */
    NULL, /* g_profile_Ykgr — REL module, not available */
    NULL, /* g_profile_TALK — REL module, not available */
    NULL, /* g_profile_Obj_Crope — REL module, not available */
    NULL, /* g_profile_Obj_Bombf — REL module, not available */
    NULL, /* g_profile_Obj_BkLeaf — REL module, not available */
    NULL, /* g_profile_Tag_Mhint — REL module, not available */
    NULL, /* g_profile_Tag_Mmsg — REL module, not available */
    NULL, /* g_profile_Tag_Mwait — REL module, not available */
    NULL, /* g_profile_Tag_Mstop — REL module, not available */
    NULL, /* g_profile_Tag_Stream — REL module, not available */
    NULL, /* g_profile_Tag_Sppath — REL module, not available */
    NULL, /* g_profile_Tag_Wljump — REL module, not available */
    NULL, /* g_profile_Tag_TWGate — REL module, not available */
    NULL, /* g_profile_Tag_Lv6Gate — REL module, not available */
    NULL, /* g_profile_Tag_Lv7Gate — REL module, not available */
    NULL, /* g_profile_Tag_Lv8Gate — REL module, not available */
    NULL, /* g_profile_Tag_TheBHint — REL module, not available */
    NULL, /* g_profile_Tag_Assist — REL module, not available */
    NULL, /* g_profile_DEMO00 — REL module, not available */
    NULL, /* g_profile_TAG_CAMERA — REL module, not available */
    NULL, /* g_profile_TAG_CHKPOINT — REL module, not available */
    &g_profile_TAG_EVENT,
    NULL, /* g_profile_TAG_EVT — REL module, not available */
    NULL, /* g_profile_TAG_TELOP — REL module, not available */
    NULL, /* g_profile_TAG_HOWL — REL module, not available */
    &g_profile_TAG_MSG,
    NULL, /* g_profile_TAG_LANTERN — REL module, not available */
    NULL, /* g_profile_Tag_Mist — REL module, not available */
    NULL, /* g_profile_DMIDNA — REL module, not available */
    &g_profile_KY_THUNDER,
    &g_profile_VRBOX,
    &g_profile_VRBOX2,
    NULL, /* g_profile_BG — REL module, not available */
    NULL, /* g_profile_SET_BG_OBJ — REL module, not available */
    NULL, /* g_profile_BG_OBJ — REL module, not available */
    NULL, /* g_profile_MIRROR — REL module, not available */
    NULL, /* g_profile_MOVIE_PLAYER — REL module, not available */
    &g_profile_TITLE,
    NULL, /* g_profile_FR — REL module, not available */
    NULL, /* g_profile_ECONT — REL module, not available */
    NULL, /* g_profile_MG_ROD — REL module, not available */
    NULL, /* g_profile_E_ARROW — REL module, not available */
    NULL, /* g_profile_BULLET — REL module, not available */
    NULL, /* g_profile_SWHIT0 — REL module, not available */
    NULL, /* g_profile_E_TH_BALL — REL module, not available */
    NULL, /* g_profile_TAG_EVTAREA — REL module, not available */
    NULL, /* g_profile_TAG_EVTMSG — REL module, not available */
    NULL, /* g_profile_TAG_KMSG — REL module, not available */
    NULL, /* g_profile_TAG_PUSH — REL module, not available */
    NULL, /* g_profile_E_MK_BO — REL module, not available */
    NULL, /* g_profile_E_MM_MT — REL module, not available */
    NULL, /* g_profile_OBJ_KBOX — REL module, not available */
    NULL, /* g_profile_OBJ_FW — REL module, not available */
    NULL, /* g_profile_B_GOS — REL module, not available */
    NULL, /* g_profile_OBJ_YSTONE — REL module, not available */
    NULL, /* g_profile_MANT — REL module, not available */
    NULL, /* g_profile_CROD — REL module, not available */
    NULL, /* g_profile_OBJ_PLEAF — REL module, not available */
    NULL, /* g_profile_OBJ_KBACKET — REL module, not available */
    NULL, /* g_profile_OBJ_YBAG — REL module, not available */
    NULL, /* g_profile_OBJ_PUMPKIN — REL module, not available */
    NULL, /* g_profile_OBJ_AUTOMATA — REL module, not available */
    NULL, /* g_profile_OBJ_GADGET — REL module, not available */
    NULL, /* g_profile_OBJ_KAGO — REL module, not available */
    NULL, /* g_profile_Obj_Carry — REL module, not available */
    NULL, /* g_profile_Obj_Stone — REL module, not available */
    NULL, /* g_profile_OBJ_HB — REL module, not available */
    NULL, /* g_profile_NPC_INKO — REL module, not available */
    NULL, /* g_profile_BD — REL module, not available */
    NULL, /* g_profile_Obj_Eff — REL module, not available */
    &g_profile_WPILLAR,
    &g_profile_WMARK,
    NULL, /* g_profile_E_BI — REL module, not available */
    NULL, /* g_profile_E_BI_LEAF — REL module, not available */
    NULL, /* g_profile_START_AND_GOAL — REL module, not available */
    NULL, /* g_profile_NPC_DF — REL module, not available */
    NULL, /* g_profile_ARROW — REL module, not available */
    NULL, /* g_profile_PATH_LINE — REL module, not available */
    NULL, /* g_profile_TAG_ALLMATO — REL module, not available */
    NULL, /* g_profile_Obj_Timer — REL module, not available */
    NULL, /* g_profile_SCENE_EXIT — REL module, not available */
    &g_profile_CAMERA,
    &g_profile_CAMERA2,
    NULL, /* g_profile_SUSPEND — REL module, not available */
    NULL, /* g_profile_GRASS — REL module, not available */
    &g_profile_KYEFF,
    &g_profile_KYEFF2,
    &g_profile_MSG_OBJECT,
    &g_profile_MENUWINDOW,
    &g_profile_TIMER,
    &g_profile_METER2,
    &g_profile_GAMEOVER,
    NULL, /* sentinel */
};

void pal_profile_list_init(void) {
    g_fpcPf_ProfileList_p = s_pc_profile_list;
    fprintf(stdout, "[PAL] Profile list initialized (792 entries, 45 available)\n");
    fflush(stdout);
}

#endif /* PLATFORM_PC */
